const adjectives = [
  // Texture-based
  "Wobbly",
  "Sparkly",
  "Fluffy",
  "Squeaky",
  "Squishy",
  "Fuzzy",
  "Slippery",
  "Bumpy",
  "Silky",
  "Bubbly",
  // Movement-based
  "Zigzagging",
  "Bouncing",
  "Twirling",
  "Prancing",
  "Spinning",
  "Floating",
  "Dancing",
  "Hopping",
  "Swaying",
  "Tumbling",
  // Sound-based
  "Whistling",
  "Squelchy",
  "Whispering",
  "Jingling",
  "Humming",
  "Chirping",
  "Buzzing",
  "Melodious",
  "Giggling",
  "Tinkling",
  // State-of-being
  "Dizzy",
  "Whimsical",
  "Drowsy",
  "Mischievous",
  "Gleaming",
  "Dazzling",
  "Puzzled",
  "Befuddled",
  "Jolly",
  "Quirky",
  // Unusual descriptors
  "Pompous",
  "Cosmic",
  "Mystical",
  "Rickety",
  "Wonky",
  "Zany",
  "Topsy-turvy",
  "Higgledy-piggledy",
  "Bamboozled",
  "Discombobulated",
];

const objects = [
  // Kitchen items
  "Teapot",
  "Waffle",
  "Spatula",
  "Toaster",
  "Kettle",
  "Spork",
  "Noodle",
  "Pickle",
  "Biscuit",
  "Meatball",
  // Musical items
  "Banjo",
  "Kazoo",
  "Tambourine",
  "Trombone",
  "Accordion",
  "Triangle",
  "Didgeridoo",
  "Ukulele",
  "Cowbell",
  "Harmonica",
  // Random objects
  "Umbrella",
  "Unicycle",
  "Sock",
  "Potato",
  "Balloon",
  "Flamingo",
  "Coconut",
  "Pineapple",
  "Cactus",
  "Lampshade",
  // Silly items
  "Doodad",
  "Whatchamacallit",
  "Gizmo",
  "Doohickey",
  "Thingamabob",
  "Wigwam",
  "Paddywack",
  "Knickknack",
  "Dinglehopper",
  "Whirligig",
  // More random fun
  "Monocle",
  "Mustache",
  "Bobblehead",
  "Squeegee",
  "Pickle",
  "Bagpipe",
  "Toupee",
  "Kaleidoscope",
  "Slinky",
  "Hodgepodge",
];

export function generateName(): string {
  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomObject = objects[Math.floor(Math.random() * objects.length)];

  return `${randomAdjective} ${randomObject}`;
}
